In [1]:
## Python Numpy library
## In data science EDA(explority data analysis and feature engineering we use numpy)
### How to make array in numpy and use in eda

In [ ]:
# Numpy is a general purpose array-processing package .It provides a high performance multidimensional array object and tools for working with these arrays.It is a fundamental package for sciencific computing with Python

In [4]:
##  What is an array?
## An array is a data structure that store the value of same datatype and this is the main difference between list and array.While list can contain different types ,in array in python only contain value of same datatype

In [6]:
### import the library
import numpy as np # np is alias and numpy is package if I want to write any inbuild function we can write as alias.then function name


In [10]:
## how to make array it can be single or multidimensional array
lst=[1,2,3,4] 
# now convert list/ or any object in array (single dimensional)
arr=np.array(lst)

In [11]:
type(arr) ## nd is a generic array 

numpy.ndarray

In [12]:
arr.shape ## here one dimensional means one row who thats why 4,0

(4,)

In [21]:
## now I want two dimensional array means I have rows and column as well means nested arry
lst1=[1,3,5,6,7]
lst2=[2,5,6,8,9]
lst3=[8,9,5,6,4]
arr1=np.array([lst1,lst2,lst3])


In [23]:
arr1.shape # now see three row and 5 column

(3, 5)

In [24]:
## indexing in array
arr[3] ## elements retrive in array

4

In [26]:
### May I change  elements in array yes we can change
arr[3]=5


In [27]:
arr

array([1, 2, 3, 5])

In [29]:
arr[1:] # we can retrive values as per range like slicing

array([2, 3, 5])

In [31]:
arr[-1] # retrive last element

5

In [33]:
arr[:-1] # retrive the elements except last element

array([1, 2, 3])

In [38]:
arr[::-1]

array([5, 3, 2, 1])

In [36]:
arr[::-2]

array([5, 2])

In [39]:
## multi dimension  array indexing

In [40]:
arr1[:,1]# : means whole row and just first column

array([3, 5, 9])

In [41]:
arr1[1:,1:3] # in slicing if I write 3 it retrive the before element

array([[5, 6],
       [9, 5]])

In [43]:
arr1[1:,3:]

array([[8, 9],
       [6, 4]])

In [44]:
arr1

array([[1, 3, 5, 6, 7],
       [2, 5, 6, 8, 9],
       [8, 9, 5, 6, 4]])

In [50]:
# Now I want to retrive last two column
arr1[:,3:]

array([[6, 7],
       [8, 9],
       [6, 4]])

In [51]:
## Other things to do in array in EDA point of view
arr

array([1, 2, 3, 5])

In [54]:
arr<2# see here 1<2 this true so it says true and then 

array([ True, False, False, False])

In [55]:
# now if I want to retrive the element which is less that just placed the entire part inside the indexing
arr[arr<2]

array([1])

In [56]:
arr.shape

(4,)

In [57]:
arr1.shape

(3, 5)

In [58]:
arr1

array([[1, 3, 5, 6, 7],
       [2, 5, 6, 8, 9],
       [8, 9, 5, 6, 4]])

In [59]:
## can we change the  shape to 5,3
arr1.reshape(5,3)

array([[1, 3, 5],
       [6, 7, 2],
       [5, 6, 8],
       [9, 8, 9],
       [5, 6, 4]])

In [60]:
arr1.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [68]:
## mechanism to create an array
print(np.arange(1,10,1)) # start ,totalno,stop
np.arange(1,20,2).reshape(2,5) # as it is 10 so lots of combination 2,5 5,2 ,10,1 etc

[1 2 3 4 5 6 7 8 9]


array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [69]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [70]:
arr*arr

array([ 1,  4,  9, 25])

In [71]:
arr1

array([[1, 3, 5, 6, 7],
       [2, 5, 6, 8, 9],
       [8, 9, 5, 6, 4]])

In [72]:
arr1*2 ## it can multiply by 2

array([[ 2,  6, 10, 12, 14],
       [ 4, 10, 12, 16, 18],
       [16, 18, 10, 12,  8]])

In [73]:
arr1

array([[1, 3, 5, 6, 7],
       [2, 5, 6, 8, 9],
       [8, 9, 5, 6, 4]])

In [74]:
arr1*arr1

array([[ 1,  9, 25, 36, 49],
       [ 4, 25, 36, 64, 81],
       [64, 81, 25, 36, 16]])

In [75]:
## Another in build functions
np.ones((5,3)) # five rows of 1 and three columns of 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [76]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [80]:
### Can arrays be a random
np.random.randint(10,50) 

33

In [82]:
np.random.randint(10,50,4).reshape(2,2) # I can also mention size as well

array([[16, 36],
       [34, 34]])